In [6]:
import numpy as np

numbers = np.array([1, 2, 3, 4])
print(numbers)
numbers.dtype

[1 2 3 4]


dtype('int32')

In [16]:
import numpy as np

matrix = np.array([
    [5, 10, 15], 
    [20, 25, 30], 
    [35, 40, 45]
])

print(matrix[:, :2])  # 取所有行的相近两列
print('***' * 10)
print(matrix[:, [0, 2]])  # 取所有行任意两列
print('===' * 20)
second_column_25 = (matrix[:, 1] == 25)
print(second_column_25)
print(matrix[second_column_25, :])

[[ 5 10]
 [20 25]
 [35 40]]
******************************
[[ 5 15]
 [20 30]
 [35 45]]
[False  True False]
[[20 25 30]]


In [8]:
import numpy as np

matrix = np.array([
    [5, 10, 15], 
    [20, 25, 30], 
    [35, 40, 45]
])
matrix.sum(axis=1)

array([ 30,  75, 120])

In [9]:
import numpy as np

matrix = np.array([
    [5, 10, 15], 
    [20, 25, 30], 
    [35, 40, 45]
])
matrix.sum(axis=0)

array([60, 75, 90])

In [13]:
import numpy as np

print(np.arange(15))
a = np.arange(15).reshape(3, 5)
a

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])