In [1]:
from sklearn import datasets  #导入数据集包
iris = datasets.load_iris()  #加载鸢尾花数据集

In [16]:
len(iris.target)

150

In [11]:
print 'iris.data:', iris.data  #用来分类样本的特征

iris.data: [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.1 1.5 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 

In [12]:
print 'iris.target:', iris.target #数据集的目标值

iris.target: [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [2]:
import numpy as np  #导入NumPy库
import pandas as pd  #导入Pandas库
import matplotlib.pyplot as plt  #导入matplotlib库

In [19]:
iris_X = iris.data  #将样本特征值设置为X
iris_y = iris.target  # 将目标值值设置为y

In [9]:
from sklearn.model_selection import train_test_split #导入数据集分离模块
X_train, X_test, y_train, y_test = train_test_split(iris_X, iris_y, test_size=0.3)
#划分为训练集和测试集数据
print(y_test)

[2 2 1 0 0 1 1 0 0 0 1 0 0 1 2 2 2 1 2 2 1 0 1 0 2 1 1 2 1 1 0 2 1 0 1 1 2
 1 0 0 0 0 0 0 2]


In [21]:
print X_train.shape #打印X_train数组形状
print y_train.shape #打印y_train数组形状
print X_test.shape  #打印X_test数组形状
print y_test.shape  #打印y_test数组形状

(105L, 4L)
(105L,)
(45L, 4L)
(45L,)


In [35]:
from sklearn.linear_model import LogisticRegression #线性模型中的逻辑回归
lr = LogisticRegression()   #引入逻辑回归算法
lr.fit(X_train, y_train)  #用逻辑回归算法拟合
print (lr.coef_)  #打印逻辑回归预测参数

[[ 0.40071709  1.30869148 -2.08884003 -0.90992701]
 [ 0.1816206  -1.12005735  0.65981272 -1.37145257]
 [-1.38479191 -1.56381736  2.08647159  2.3382551 ]]


In [36]:
y_pred = lr.predict(X_test)  #对测试集的数据进行预测
from sklearn import metrics  #导入性能指标库
# 用scikit-learn计算MSE
print "MSE:",metrics.mean_squared_error(y_test, y_pred)
# 用scikit-learn计算RMSE
print "RMSE:",np.sqrt(metrics.mean_squared_error(y_test, y_pred))

MSE: 0.06666666666666667
RMSE: 0.2581988897471611


In [27]:
from sklearn.tree import DecisionTreeClassifier  #导入决策树模块
tree_clf = DecisionTreeClassifier( max_depth=2 ) #设定决策树算法
tree_clf.fit(X_train, y_train) #拟合

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=2,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [28]:
y_pred_tree = tree_clf.predict(X_test)
# 用scikit-learn计算MSE
print "MSE:",metrics.mean_squared_error(y_test, y_pred_tree)
# 用scikit-learn计算RMSE
print "RMSE:",np.sqrt(metrics.mean_squared_error(y_test, y_pred_tree))

MSE: 0.044444444444444446
RMSE: 0.21081851067789195


In [33]:
from sklearn.neighbors import KNeighborsClassifier #导入KNN最近邻分类包
knn = KNeighborsClassifier() #设定K近邻算法
knn.fit(X_train,y_train)  #拟合
y_pred_knn = tree_clf.predict(X_test) #预测
# 用scikit-learn计算MSE
print "MSE:",metrics.mean_squared_error(y_test, y_pred_knn)
# 用scikit-learn计算RMSE
print "RMSE:",np.sqrt(metrics.mean_squared_error(y_test, y_pred_knn))

MSE: 0.044444444444444446
RMSE: 0.21081851067789195


In [34]:
from sklearn import svm  #导入支持向量机svm包
svm = svm.SVC() #设定svm算法
svm.fit(X_train,y_train)  #拟合
y_pred_svm = tree_clf.predict(X_test)
# 用scikit-learn计算MSE
print "MSE:",metrics.mean_squared_error(y_test, y_pred_svm)
# 用scikit-learn计算RMSE
print "RMSE:",np.sqrt(metrics.mean_squared_error(y_test, y_pred_svm))

MSE: 0.044444444444444446
RMSE: 0.21081851067789195
